### ISSUE TITLE
[1.4.3] Custom font not showing up

### ISSUE THREAD

**Issue by mateosss** [hartwork/grub2-theme-preview#19]
Following discussion from #18 in which unicode font was shown instead of the theme's custom one.
I think I found why it happens.
The last `loadfont` of the resulting grub.cfg is the font that gets to be used.
In `_make_grub_cfg_load_our_theme` the `prolog` list loads the correct font before appending the source grub.cfg.
The source grub.cfg seems to overwrite that one with the default unicode. It also tries to load the custom font as well, but I guess the path in the source grub.cfg may be incorrect from the qemu point of view, and so it keeps the unicode font.

In my case hardcoding the element `"loadfont $prefix/themes/DEMO/googlesans.pf2"` inside `epilog_chunks` solves it.

To summarize:

**source grub.cfg**
```sh
loadfont $font # Loads unicode font
loadfont ($root)/boot/grub/themes/Matter/googlesans.pf2 # Loads custom font from theme
```

**resulting non-working grub.cfg (current)**
```sh
# Prolog
loadfont $prefix/themes/DEMO/googlesans.pf2

# Contents of source grub.cfg
loadfont $font # Loads unicode font
loadfont ($root)/boot/grub/themes/Matter/googlesans.pf2 # Loads custom font from theme, probably an invalid path

# Epilog
...
```

**resulting working grub.cfg (proposed)**
```sh
# Prolog
...

# Contents of source grub.cfg
loadfont $font # Loads unicode font
loadfont ($root)/boot/grub/themes/Matter/googlesans.pf2 # Loads custom font from theme, probably an invalid path

# Epilog
loadfont $prefix/themes/DEMO/googlesans.pf2
```

I would make a PR, but don't really have the time to read too much into the script to check it does not break other things.

**Comment by mateosss** [comment]
Before
![before](https://user-images.githubusercontent.com/5622899/85955870-104d8d80-b958-11ea-96e4-db59f245f2d9.png)
After
![after](https://user-images.githubusercontent.com/5622899/85955872-12175100-b958-11ea-9099-07cc8782248d.png)

**Comment by hartwork** [comment]
Mateo, thanks for the report, interesting hint on font file location, I like it :+1:

**Comment by mateosss** [comment]
Thanks to you! I'll probably be using this package in the future for quick tests of my theme instead of a virtual machine.

**Comment by hartwork** [comment]
Glad to hear, that's what I made this tool for.

I had a closer look at the font situation now:
- In my tests both `amaticsc64.pf2` and `googlesans.pf2` get loaded successfully as confirmed by command `lsfonts` in a GRUB shell.
- When the same font file is loaded multiple times, `lsfonts` will list the font multiple times.
- I found an earlier comment of mine in code that states that the last font loaded becomes the default (or fallback font): https://github.com/hartwork/grub2-theme-preview/blob/99e6fa237781bd394fa0173b37811a21ce9fb685/grub2_theme_preview/__main__.py#L91-L93
  I'll assume that's true :smiley: 
- Some pieces provided by my distro that also go into `grub.cfg` make it so that `unicode.pf2` is always loaded, resulting in that font to be the last and hence default in my local case.
  ```bash
  [..]
  if [ x$feature_default_font_path = xy ] ; then
      font=unicode
  else
      [..]
      font="/grub/unicode.pf2"
  fi
  
  if loadfont $font ; then
      [..]
  fi
  [..]
  ```
- Interestingly, `lsfonts` lists `Google Sans Regular 32` while `theme.txt` says `GoogleSans Regular 32` (with a single space less). Once I add that space in `Google[ ]Sans` in `theme.txt`, the font gets bigger (despite `unicode.pf2` still being the fallback font) which I guess means that it's using `googlesans.pf2` to render now. So my guess is that your appending `loadfont $prefix/themes/DEMO/googlesans.pf2` above changed the default font and hence made things appear to work despite font name lookup failure.

It would be great if you could check `lsfonts` output (after hitting `c` to get into the shell) if it says `GoogleSans` or `Google Sans` there for you. Let's then think how to best address the result of that test. What do you think?

PS: I made `--debug` dump the eventual `grub.cfg``content about to be used in the generated image on Git `master` now.

**Comment by mateosss** [comment]
Yes that was it, the space characater!
I didn't know about the lsfonts command, very useful.

Currently lsfonts in qemu gives:
```
Unifont Regular 16              (1)
Google Sans 32                  (2)
Unifont Regular 16              (3)
```

While the same grub.cfg in a virtualbox virtual machine gives

```
Google Sans 32
Unifont Regular 16
```

(1) and (2) come from the `prolog_chunks` part and (3) from the source grub.cfg, Google Sans 32 is not appended a second time probably because of an incorrect path on qemu side.

On one hand it would be nice to match the final implementation, on the other it may be too troublesome and it works pretty well already considering it was a fault on my side.

If I understand correctly, the theme is copied into `/boot/grub/themes/DEMO` for the qemu image, maybe the folder structure could match the original one, and so grub.cfg will directly work for qemu as well without the need for the prolog/epilog chunks. But at the same time, if the theme is not already installed (as was mine) or is on another folder then you would still need to manually set the theme and load the fonts in the prolog/epilog chunks. Maybe a flag to differentiate between those two cases? 

Just throwing ideas, in any case, the tool already works pretty well for me, and the issue is solved considering the mispelling.

**Comment by hartwork** [comment]
I think I started add `loadfont` commands in the first place, because if the theme needs custom fonts then before installation `/boot/grub/grub.cfg` is not going to mention those. On my system, file `/etc/grub.d/00_header` handles the font the user put into `GRUB_FONT` in `/etc/default/grub` but it takes a call to `grub-mkconfig` or Debian/Ubuntu `update-grub` to propagate and potentially break the old/current theme. From what you mention it sounds to me like adding an option `--vanilla-grub-cfg` that would be off by default and if given stops adding timeout, loadfont etc on the fly. It would not be hard to implement. Would you use such an option? Did you have other adjustments to the prolog/epilog approach in mind?

Regarding the font name, it's interesting that some versions of GRUB say "Regular" and some don't. Maybe there is a way to modify in the `.pf2` file in a way to yield constant font names across GRUB versions to make the theme work for all versions of GRUB. Or is something making this a non-issue that I am missing?

For the in-image theme folder name, I see e.g. `/boot/grub/themes/starfield` locally so `/boot/grub/themes/DEMO` seems to match the scheme. Is your point that it should be `/boot/grub/themes/Matter` in your case? If that's the idea, I could take the last part of the full path after making absolute and use that for a name? I wonder if there can be cases other than plain `/` where that doesn't work.

So I'm happy improve on this more. Let me know what you think.

**Comment by mateosss** [comment]
> Would you use such an option?

Probably no, considering I now know I was mispelling the font names, the emulation for me at least, works perfectly now as it is.

> Regarding the font name, it's interesting that some versions of GRUB say "Regular" and some don't. Maybe there is a way to modify in the `.pf2` file in a way to yield constant font names across GRUB versions to make the theme work for all versions of GRUB. Or is something making this a non-issue that I am missing?

I'm not really sure what as to what you are referring to. In my case the `unicode.pf2` always seem to have the `Unifont Regular  16` name. When you create a grub font with `grub-mkfont` from a ttf file there is a `--name` and a `--size` option, but the `Regular`/`Bold`/etc in between those seems to come directly from the font.

> Is your point that it should be `/boot/grub/themes/Matter` in your case? 

Yes I was referring to that.

> If that's the idea, I could take the last part of the full path after making absolute and use that for a name? I wonder if there can be cases other than plain `/` where that doesn't work.

That I can't tell.

I guess it is not really a must, it's more of a "nice to have" that would match more closely the final implementation, but again by knowing the `lsfonts` would be enough for a theme maker to know they are mispelling a font if it looks different. And in fact, this issue will still be in the repo for future reference.

**Comment by hartwork** [comment]
Alright, it sounds like you're good with status quo. If any of that turns into a bigger itch, please comment here later or create feel to create a new ticket.

**Comment by mateosss** [comment]
Sure, thanks for your help!

**Comment by stevensonmt** [comment]
I'm not really able to follow this thread so not sure if my issue is the same. My fonts appear to load but are not applied. Only the fallback unifont is actually used. Debug output includes:
```
INFO: Appending to fonts to load: JosefinSans-Medium.pf2
INFO: Appending to fonts to load: JosefinSans-Semibold.pf2
...
if [ x$feature_default_font_path = xy ] ; then
   font=unicode
else
insmod part_msdos
insmod btrfs
set root='hd0'  # replaced by grub2-theme-preview, was 'hd1,msdos2'
if [ x$feature_platform_search_hint = xy ]; then
  search --no-floppy --fs-uuid --set=root --hint-bios=hd1,msdos2 --hint-efi=hd1,msdos2 --hint-baremetal=ahci1,msdos2  --hint-bios=hd2 --hint-efi=hd2 --hint-baremetal=ahci2  2282bec7-74b0-4f0c-a0d5-d1e67e818c6b
else
  search --no-floppy --fs-uuid --set=root 2282bec7-74b0-4f0c-a0d5-d1e67e818c6b
fi
    font="/usr/share/grub/unicode.pf2"
fi

if loadfont $font ; then
  set gfxmode=800x600x32
  load_video
  insmod gfxterm
  set locale_dir=$prefix/locale
  set lang=en_US
  insmod gettext
fi
...
loadfont ($root)/grub/fonts/FantasqueSansMono.pf2
loadfont ($root)/grub/fonts/HighVoltage.pf2
loadfont ($root)/grub/themes/my_theme/JosefinSans-Medium.pf2
loadfont ($root)/grub/themes/my_theme/JosefinSans-Semibold.pf2
```
And from the grub shell in QEMU `lsfonts` gives:
```
Loaded fonts:
Unifont Regular 16
=JosefinSasnsSemiBold Regular 16
Josefin Sans Regular 16
Unifont Regular 16
```
Tips?
