### ISSUE TITLE
error in qemu no bootable devices

### ISSUE THREAD

**Issue by vedvarshith** [hartwork/grub2-theme-preview#23]
i many times tried to install macos and windows 10 in qemu but it shows me this error
![Screenshot_2020-10-15_19-06-10](https://user-images.githubusercontent.com/70155237/96138169-1e311980-0f1b-11eb-8603-243c7cf60b0e.png)
![Uploading Screenshot_2020-10-15_19-08-07.png…]()

**Comment by hartwork** [comment]
Please elaborate how this is connected to grub2-theme-preview and how you invoked grub2-theme-preview. Thanks!

**Comment by vedvarshith** [comment]
i will try

**Comment by vedvarshith** [comment]
but din't help can you give a scree shot please i will show you my screenshot 
![image](https://user-images.githubusercontent.com/70155237/96237768-525c1700-0fbb-11eb-96f1-d7a3affe5a03.png)

**Comment by hartwork** [comment]
`--verbose --debug` was referring to `grub2-theme-preview`, not QEMU. What you're trying looks like zero related to `grub2-theme-preview`, just QEMU. That's rather ignorant in my book. Please find some QEMU help medium or buy commercial support from someone instead of abusing volunteers of some vaguely related project.
