### ISSUE TITLE
ERROR: [Errno 2] GRUB platform directory "/usr/lib/grub/x86_64-efi" not found

### ISSUE THREAD

**Issue by thekarananand** [hartwork/grub2-theme-preview#302]
i am using fedora 40

![image](https://github.com/user-attachments/assets/b6b573f5-eb18-4c28-9fc9-e69e6d358243)

![image](https://github.com/user-attachments/assets/442b10ad-84e7-4ec4-b96e-30c51ee1bdd4)

**Comment by hartwork** [comment]
Hi @thekarananand, grub2-theme-preview looks for path `/sys/firmware/efi` to determine whether your hard is EFI or not. So that needs sysfs mounted at `/sys`, e.g.:

```console
# mount | grep "/sys "
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
```

Could you check if you have `/sys` mouinted and file `/sys/firmware/efi` available?

PS: The related code is… https://github.com/hartwork/grub2-theme-preview/blob/c973077c413cacd27bbece82e415ea257deabdd6/grub2_theme_preview/__main__.py#L356-L365 …if curious.

**Comment by hartwork** [comment]
> Could you check if you have `/sys` mouinted and file `/sys/firmware/efi` available?

@thekarananand any news?

**Comment by Bingo90** [comment]
Hey, I have the same issue. I'm on Fedora 41 KDE and /sys/firmware/efi exists.

**Comment by Bingo90** [comment]
@hartwork 
Hey, I have the same issue. I'm on Fedora 41 KDE and /sys/firmware/efi exists.

**Comment by hartwork** [comment]
@Bingo90 could you install package `grub2-efi-x64-modules`, try again, and report back? According to the listing at https://packages.fedoraproject.org/pkgs/grub2/grub2-efi-x64-modules/fedora-41-updates.html#files it's the package that contains the missing files for you. Thanks!

**Comment by Bingo90** [comment]
@hartwork Yeah, that did the trick! Thanks ^^
