### ISSUE TITLE
Use Custom Config

### ISSUE THREAD

**Issue by Jacksaur** [hartwork/grub2-theme-preview#47]
Apologies if there's already a flag for this, but I couldn't seem to work it out myself:
The preview always displays with the same Gentoo, Debian, Memtest options. Is there a way to get it to read from my system's own grub.cfg file, such that I can quickly preview my custom menu changes?

**Comment by hartwork** [comment]
Hi @Jacksaur , yes there is. By default, `grub2-theme-preview` tries to read both `/boot/grub2/grub.cfg` and `/boot/grub/grub.cfg` and fails back to Gentoo-Debian-Memtest if neither of the two worked, either because they are missing or because of insufficient read permissions. So if you location matches either of these, it needs a change in file permissions (or use of `sudo`). If you location differs, then argument `--grub-cfg PATH` will allow for that custom location. What do you think?

**Comment by Jacksaur** [comment]
Ah yeah, grub.cfg had no read permissions for me. Thanks!
